<div class="container mt-4" style="max-width: 600px;">
    <h2 class="text-center mb-4">Buscar Usuario</h2>

    <form method="get" action="/admin/usuarios/buscar">
        <div class="input-group">
            <input 
                type="text" 
                name="q" 
                class="form-control" 
                placeholder="Buscar por CUI, Carné o Registro Personal"
                required>
            
            <button class="btn btn-primary" type="submit">Buscar</button>
        </div>
    </form>
</div>
