<div class="pagina">

    <img src="<?= $this->arte ?>" class="fondo">

    <div class="<?= $this->esPrimera ? 'contenido-primera' : 'contenido-normal' ?>">

        <?php if ($this->esPrimera): ?>

            <p class="titulo">
                <?= $this->titulo ?>
            </p>

            <p class="parrafo">
                <?= $this->parrafo ?>
            </p>

        <?php endif; ?>

        <?php if (!empty($this->rows)): ?>

            <table>
                <thead>
                    <tr>
                        <th width="70%">ACTIVIDAD</th>
                        <th width="30%">CRÉDITOS</th>
                    </tr>
                </thead>

                <tbody>

                    <?php foreach ($this->rows as $a): ?>

                        <tr>
                            <td><?= $a->actividad ?></td>
                            <td align="center"><?= $a->credito ?></td>
                        </tr>

                    <?php endforeach; ?>

                    <?php if ($this->esUltima): ?>
                        <tr>
                            <td><strong>TOTAL</strong></td>
                            <td align="center">
                                <strong><?= $this->total ?></strong>
                            </td>
                        </tr>
                    <?php endif; ?>

                </tbody>
            </table>

        <?php endif; ?>

        <?php if ($this->esUltima): ?>

            <p class="fecha">
                <?= $this->fecha_texto ?>
            </p>

            <div class="firma">

                <div class="linea"></div>

                <p>
                    <strong><?= $this->responsable ?></strong><br>

                    <?= $this->texto_firma ?><br>

                    <?= $this->institucion ?><br>

                    **********ÚLTIMA LÍNEA**********
                </p>

            </div>

        <?php endif; ?>

    </div>

</div>